# Generated by Django 5.2 on 2025-04-28 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_memo', models.CharField(default='P', max_length=10, verbose_name='Purchase (P), Memo (M), Bargain (B)')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('book_no', models.IntegerField()),
                ('order_no', models.IntegerField(unique=True)),
                ('tax_invoice', models.CharField(blank=True, max_length=50, null=True)),
                ('supplier', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('stone', models.CharField(max_length=50)),
                ('heating', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('shape', models.CharField(blank=True, max_length=50, null=True)),
                ('cutting', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('carats', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Weight in carats')),
                ('currency', models.CharField(default='THB', max_length=5)),
                ('price_cur_per_unit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit', models.CharField(default='CT', max_length=5)),
                ('total_thb', models.DecimalField(decimal_places=2, max_digits=15)),
                ('weight_per_piece', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('price_usd_per_ct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_usd_per_piece', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rate_avg_2019', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('credit_term', models.CharField(blank=True, max_length=50, null=True)),
                ('target_size', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.IntegerField(unique=True)),
                ('date', models.DateTimeField()),
                ('total_price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price_thb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
    ]
