# Generated by Django 5.2 on 2025-04-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='order_no',
            field=models.IntegerField(),
        ),
    ]
