# Generated by Django 5.2 on 2025-05-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorderraw',
            name='success',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderraw',
            name='success',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierorderraw',
            name='success',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
