# Generated by Django 5.2 on 2025-04-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_clientorder_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorder',
            name='order_no',
            field=models.IntegerField(),
        ),
    ]
