# Generated by Django 5.2 on 2025-05-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_clientorderraw_success_alter_orderraw_success_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierorderraw',
            name='error',
        ),
        migrations.RemoveField(
            model_name='supplierorderraw',
            name='success',
        ),
    ]
