# Generated by Django 5.2 on 2025-05-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_supplierorderraw_error_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientorderraw',
            name='error',
        ),
        migrations.RemoveField(
            model_name='clientorderraw',
            name='success',
        ),
        migrations.RemoveField(
            model_name='orderraw',
            name='error',
        ),
        migrations.RemoveField(
            model_name='orderraw',
            name='success',
        ),
        migrations.RemoveField(
            model_name='supplierorder',
            name='tax_invoice',
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='book_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='price_usd_per_ct',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='price_usd_per_piece',
            field=models.DecimalField(decimal_places=3, max_digits=13),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='total_usd',
            field=models.DecimalField(decimal_places=3, max_digits=13),
        ),
    ]
