# Generated by Django 5.2 on 2025-04-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_supplierorder_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorder',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
