# Generated by Django 5.2 on 2025-04-29 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_supplierorder_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplierorder',
            unique_together={('order_no', 'number', 'stone', 'shape')},
        ),
    ]
