# Generated by Django 5.2 on 2025-05-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_clientorderraw_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorder',
            name='order_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='total_usd',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
    ]
