# Generated by Django 5.2 on 2025-05-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_supplierorder_order_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorder',
            name='book_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='order_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='price_usd_per_piece',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='stone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='clientorderraw',
            unique_together={('source_file', 'sheet_name', 'row_index')},
        ),
        migrations.AlterUniqueTogether(
            name='orderraw',
            unique_together={('source_file', 'sheet_name', 'row_index')},
        ),
        migrations.AlterUniqueTogether(
            name='supplierorderraw',
            unique_together={('source_file', 'sheet_name', 'row_index')},
        ),
        migrations.AddConstraint(
            model_name='clientorderraw',
            constraint=models.UniqueConstraint(fields=('source_file', 'sheet_name', 'row_index'), name='unique_client_raw_order_lot'),
        ),
        migrations.AddConstraint(
            model_name='orderraw',
            constraint=models.UniqueConstraint(fields=('source_file', 'sheet_name', 'row_index'), name='unique_raw_order_lot'),
        ),
        migrations.AddConstraint(
            model_name='supplierorderraw',
            constraint=models.UniqueConstraint(fields=('source_file', 'sheet_name', 'row_index'), name='unique_supplier_raw_order_lot'),
        ),
    ]
