# Generated by Django 5.2 on 2025-04-29 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_supplierorder_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplierorder',
            unique_together={('order_no', 'number', 'stone', 'shape', 'color', 'cutting', 'size', 'carats')},
        ),
    ]
