# Generated by Django 5.2 on 2025-04-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_supplierorder_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplierorder',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='supplierorder',
            constraint=models.UniqueConstraint(fields=('supplier', 'order_no', 'number', 'stone', 'shape', 'color', 'cutting', 'size', 'carats'), name='unique_supplier_lot'),
        ),
    ]
