# Generated by Django 5.2 on 2025-05-01 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_supplierorder_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplierorder',
            unique_together={('supplier', 'order_no', 'number', 'stone', 'shape', 'color', 'cutting', 'size', 'carats')},
        ),
    ]
