# Generated by Django 5.2 on 2025-05-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_supplierorder_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorder',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('THB', 'Thai Baht'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen')], default='THB', max_length=3),
        ),
    ]
