# Generated by Django 5.2 on 2025-05-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_supplierorder_currency'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supplierorder',
            name='unique_supplier_lot',
        ),
        migrations.AlterUniqueTogether(
            name='supplierorder',
            unique_together={('supplier', 'order_no', 'number', 'stone', 'shape', 'color', 'size', 'carats', 'weight_per_piece')},
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('THB', 'Thai Baht')], default='THB', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='supplierorder',
            constraint=models.UniqueConstraint(fields=('supplier', 'order_no', 'number', 'stone', 'shape', 'color', 'size', 'carats', 'weight_per_piece'), name='unique_supplier_lot'),
        ),
        migrations.RemoveField(
            model_name='supplierorder',
            name='cutting',
        ),
    ]
