# Generated by Django 5.2 on 2025-05-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_supplierorder_unique_supplier_lot_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supplierorder',
            name='unique_supplier_lot',
        ),
        migrations.AlterUniqueTogether(
            name='supplierorder',
            unique_together={('date', 'supplier', 'order_no', 'number', 'stone', 'shape', 'color', 'size', 'carats', 'weight_per_piece', 'price_usd_per_ct')},
        ),
        migrations.AddConstraint(
            model_name='supplierorder',
            constraint=models.UniqueConstraint(fields=('date', 'supplier', 'order_no', 'number', 'stone', 'shape', 'color', 'size', 'carats', 'weight_per_piece', 'price_usd_per_ct'), name='unique_supplier_lot'),
        ),
    ]
