# Generated by Django 5.2 on 2025-04-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('date', models.DateField(unique=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('open', models.DecimalField(decimal_places=4, max_digits=10)),
                ('high', models.DecimalField(decimal_places=4, max_digits=10)),
                ('low', models.DecimalField(decimal_places=4, max_digits=10)),
                ('change_percent', models.CharField(blank=True, max_length=10, null=True)),
                ('usd_to_thb', models.DecimalField(decimal_places=4, max_digits=10)),
                ('thb_to_usd', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
    ]
