# Generated by Django 5.2 on 2025-05-01 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerate',
            name='thb_to_usd',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='usd_to_thb',
        ),
    ]
